ESF.WebClient/Controllers/AccommodationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ESF.WebClient.Filters;
using ESF.Core.Services;
using ESF.Commons.Utilities;
using WebMatrix.WebData;

namespace ESF.WebClient.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class AccommodationController : Controller
    {
        private readonly IParticipantService participantService;

        public AccommodationController(IParticipantService participantService)
        {
            Check.IsNotNull(participantService, "participantService may not be null");

            this.participantService = participantService;
        }

        [HttpGet]
        public ActionResult RequestAccommodation(Guid id)
        {
            ViewBag.Message = "This is where you request Accommodation.";
            ViewBag.ParticipantId = id;

            return View();
        }

        [HttpGet]
        public ActionResult ViewAccommodation(Guid? id)
        {
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty)
            {
                var userId = WebSecurity.CurrentUserId;

                Check.IsTrue(userId > 0, "");

                id = participantService.RetrieveParticipantIdByUserId(userId);
            }

            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            // TODO : handle the scenario where an id is manually entered in the url
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            ViewBag.Message = "This is where you view your Accommodation details.";
            ViewBag.ParticipantId = id.Value;

            return View();
        }
    }
}

ESF.WebClient/Controllers/TransportController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ESF.WebClient.Filters;
using WebMatrix.WebData;
using ESF.Commons.Utilities;
using ESF.Core.Services;
using ESF.Core.Services.Models;
using ESF.Commons.Exceptions;

namespace ESF.WebClient.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class TransportController : Controller
    {
        private readonly IParticipantService participantService;
        private readonly ITransportService transportService;
        private readonly ISportsEventService sportEventService;

        public TransportController(IParticipantService participantService, 
            ITransportService transportService, 
            ISportsEventService sportEventService)
        {
            Check.IsNotNull(participantService, "participantService may not be null");
            Check.IsNotNull(transportService, "transportService may not be null");
            Check.IsNotNull(sportEventService, "sportEventService may not be null");

            this.participantService = participantService;
            this.transportService = transportService;
            this.sportEventService = sportEventService;
        }

        [HttpGet]
        public ActionResult ViewTransport(Guid? id)
        {
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty)
            {
                var userId = WebSecurity.CurrentUserId;

                Check.IsTrue(userId > 0, "");

                id = participantService.RetrieveParticipantIdByUserId(userId);
            }

            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            // TODO : handle the scenario where an id is manually entered in the url
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            var transportRequests = transportService.FindParticipantTransportRequests(id.Value);

            ViewData.Model = transportRequests;

            ViewBag.Message = string.Format("{0}Current Transport Requests.", transportRequests.Any() ? string.Empty : "This is where you view your ");
            ViewBag.ParticipantId = id.Value;

            return View();
        }

        [HttpGet]
        public ActionResult RequestTransport(Guid id)
        {
            ViewData.Model = TempData["TransportRequestModel"] ?? new TransportRequestModel { ParticipantId = id };
            ModelState.AddModelError(string.Empty, (TempData["RequestTransportErrorMessage"] ?? string.Empty).ToString());

            var daysWithNoTransportRequests = transportService.FindDaysWithNoTransportRequests(id);
            var pickupPoints = transportService.FindPickupPoints();

            ViewBag.Days = daysWithNoTransportRequests.AsEnumerable()
                .Select(x => new SelectListItem
                {
                    Value = x.FestivalDayId.ToString(),
                    Text = x.DisplayDate
                });

            ViewBag.PickupPoints = pickupPoints.AsEnumerable()
                .Select(x => new SelectListItem
                {
                    Value = x.PickupPointId.ToString(),
                    Text = x.PickupPointName
                });


            //ViewBag.Message = "This is where you request Transport.";
            ViewBag.ParticipantId = id;

            return View();
        }

        [HttpPost]
        public ActionResult RequestTransport(TransportRequestModel transportRequestModel)
        {
            Check.IsNotNull(transportRequestModel, "transportRequestModel may not be null");

            try
            {
                transportService.CreateTransportRequest(transportRequestModel);
            }
            catch (BusinessException bex)
            {
                TempData["RequestTransportErrorMessage"] = bex.Message;
                TempData["TransportRequestModel"] = transportRequestModel;
                return RedirectToAction("RequestTransport", new { id = transportRequestModel.ParticipantId });
            }

            return RedirectToAction("ViewTransport", new { id = transportRequestModel.ParticipantId });
        }

        [HttpGet]
        public ActionResult CancelTransportRequest(Guid participantid, Guid transportRequestid)
        {
            try
            {
                transportService.CancelTransportRequest(transportRequestid);
            }
            catch (BusinessException bex)
            {
                TempData["TransportRequestDeleteErrorMessage"] = bex.Message;
            }

            return RedirectToAction("ViewTransport", new {id = participantid});
        }
    }
}

ESF.WebClient/Views/Transport/RequestTransport.cshtml
@model ESF.Core.Services.Models.TransportRequestModel

@{
    ViewBag.Title = "Request Transport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Request Transport</h2>
<p>
    @ViewBag.Message
</p>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Transport Request</legend>

        @Html.HiddenFor(model => model.ParticipantId)

        <div class="editor-label">
            @Html.LabelFor(model => model.FestivalDayId, "Day")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FestivalDayId", (IEnumerable<SelectListItem>)ViewBag.Days)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TransportPickupPointId, "Pickup Point")
        </div>
        <div class="editor-field">
            @Html.DropDownList("TransportPickupPointId", (IEnumerable<SelectListItem>)ViewBag.PickupPoints)
        </div>

        <p>
            <input type="submit" value="Sumbmit Request" />
        </p>
    </fieldset>
}

<p>
    @Html.ActionLink("Back to Details", "ViewParticipant", "Participant", new { id = ViewBag.ParticipantId }, null)
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESF.WebClient/Views/Transport/ViewTransport.cshtml
@model IEnumerable<ESF.Core.Services.TransportRequestItem>

@{
    ViewBag.Title = "View Transport Requests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Transport Requests</h2>

<p>
    @ViewBag.Message
</p>

<table>
    <tr>
        <th>
            @Html.DisplayName("Pickup Day")
        </th>
        <th>
            @Html.DisplayName("Pickup Point")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TransportPickupDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransportPickupPointName)
        </td>
        <td>
@*            @Html.ActionLink("Change Pickup Point", "ChangePickupPoint", new { transportRequestId = item.TransportRequestId }) |*@
            @Html.ActionLink("Cancel Transport Request", "CancelTransportRequest", new { participantId = item.ParticipantId, transportRequestId = item.TransportRequestId })
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Request Transport", "RequestTransport", "Transport", new { id = ViewBag.ParticipantId }, null)
</p>
<p>
    @Html.ActionLink("Next", "ViewAccommodation", "Accommodation", new { id = ViewBag.ParticipantId }, null)
</p>