ESF.WebClient/Controllers/EntertainmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ESF.WebClient.Filters;
using ESF.Core.Services;
using ESF.Commons.Utilities;
using WebMatrix.WebData;

namespace ESF.WebClient.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class EntertainmentController : Controller
    {
        private readonly IParticipantService participantService;

        public EntertainmentController(IParticipantService participantService)
        {
            Check.IsNotNull(participantService, "participantService may not be null");

            this.participantService = participantService;
        }

        [HttpGet]
        public ActionResult SignUp(Guid id)
        {
            ViewBag.Message = "This is where you Sign Up for Entertainment.";
            ViewBag.ParticipantId = id;

            return View();
        }

        [HttpGet]
        public ActionResult ViewEntertainment(Guid? id)
        {
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty)
            {
                var userId = WebSecurity.CurrentUserId;

                Check.IsTrue(userId > 0, "");

                id = participantService.RetrieveParticipantIdByUserId(userId);
            }

            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            // TODO : handle the scenario where an id is manually entered in the url
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            ViewBag.Message = "This is where you view the entertainment events that you have signed up for.";
            ViewBag.ParticipantId = id.Value;

            return View();
        }

    }
}

ESF.WebClient/Controllers/SportsEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ESF.WebClient.Filters;
using ESF.Core.Services;
using ESF.Commons.Utilities;
using WebMatrix.WebData;
using ESF.Commons.Exceptions;

namespace ESF.WebClient.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class SportsEventController : Controller
    {
        private readonly IParticipantService participantService;
        private readonly ISportsEventService sportsEventService;

        public SportsEventController(IParticipantService participantService, ISportsEventService sportsEventService)
        {
            Check.IsNotNull(participantService, "participantService may not be null");
            Check.IsNotNull(sportsEventService, "sportsEventService may not be null");

            this.participantService = participantService;
            this.sportsEventService = sportsEventService;
        }

        [HttpGet]
        public ActionResult ViewSportsEvents(Guid? id)
        {
            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty)
            {
                var userId = WebSecurity.CurrentUserId;

                Check.IsTrue(userId > 0, "");

                id = participantService.RetrieveParticipantIdByUserId(userId);
            }

            if (id.GetValueOrDefault(Guid.Empty) == Guid.Empty && WebSecurity.IsAuthenticated)
            {
                TempData["createparticipantmessage"] = "Please complete your registration";
                return RedirectToAction("CreateParticipant", "Participant");
            }

            var sportsEvents = sportsEventService.RetrieveSignedUpSportsEvents(id.Value);

            ViewData.Model = sportsEvents;
            ViewBag.Message = string.Format("{0}Sport Events that you are signed up for.", sportsEvents.Any() ? string.Empty : "This is where you view the ");
            ViewBag.ParticipantId = id.Value;

            return View();
        }

        [HttpGet]
        public ActionResult SignUpGrid(Guid id)
        {
            ViewBag.SportEventSignUpMessage = TempData["SportEventSignUpMessage"];

            var sportEvents = sportsEventService.FindSportsEventsWithParticipantSelection(id);

            ViewData.Model = sportEvents;

            ViewBag.ParticipantId = id;

            return View();
        }

        [HttpPost]
        // TODO: Get MVC Framework to Populate sportEventIds parameter.
        public ActionResult SignUpGrid(Guid participantId, Guid[] sportEventIds)
        {
            var selectedSportEventIds = new List<Guid>();

            foreach (var key in Request.Form.AllKeys.Where(x => x != "participantId"))
            {
                var sportEventGuid = Guid.Empty;
                if(Guid.TryParse(key, out sportEventGuid))
                {
                    if(Request.Form[key] == "on")
                        selectedSportEventIds.Add(sportEventGuid);
                }
            }

            if(selectedSportEventIds.Any())
            {
                try
                {
                    sportsEventService.SignUpParticipant(participantId, selectedSportEventIds);
                    return RedirectToAction("ViewSportsEvents", new {id = participantId});
                }
                catch (BusinessException bex)
                {
                    TempData["SportEventSignUpMessage"] = bex.Message;
                    RedirectToAction("SignUpGrid", new {id = participantId});
                }
            }

            TempData["SportEventSignUpMessage"] = "Please select one or more sport events.";

            return RedirectToAction("SignUpGrid", new { id = participantId });
        }

        [HttpGet]
        public ActionResult SportEventTeamSelect(Guid id)
        {
            ViewBag.SportEventTeamSelectMessage = (TempData["SportEventTeamSelectMessage"] ?? string.Empty).ToString();

            ViewData.Model = new TeamSelectionModel { ScheduledSportEventParticipantId = id };

            return View();
        }

        [HttpPost]
        public ActionResult SportEventTeamSelect(TeamSelectionModel model)
        {
            switch (model.TeamSelectionOption)
            {
                case 1: // Create Team
                    return RedirectToAction("SportEventCreateNewTeam", new { Id = model.ScheduledSportEventParticipantId });
                case 2: // Join Team
                    return RedirectToAction("SportEventSelectExistingTeam", new { Id = model.ScheduledSportEventParticipantId });
                case 3: // Available for allocation
                    sportsEventService.MakeParticipantAvailableForTeamAllocation(model.ScheduledSportEventParticipantId);

                    TempData["TeamSelectionConfirmationMessage"] = "Your interest in being allocated to a team has been registered.";

                    return RedirectToAction("TeamSelectionConfirmation");
            }

            return View();
        }

        [HttpGet]
        public ActionResult SportEventCreateNewTeam(Guid id)
        {
            ModelState.AddModelError(string.Empty, (TempData["TeamCreateErrorMessage"] ?? string.Empty).ToString());

            ViewData.Model = TempData["TeamCreateModel"] ?? new TeamCreateModel{ CaptainSportEventParticipantId = id };

            return View();
        }

        [HttpPost]
        public ActionResult SportEventCreateNewTeam(TeamCreateModel model)
        {
            try
            {
                model = sportsEventService.CreateNewSportEventTeam(model);
            }
            catch (BusinessException bex)
            {
                TempData["TeamCreateErrorMessage"] = bex.Message;
                TempData["TeamCreateModel"] = model;

                return RedirectToAction("SportEventCreateNewTeam", new { Id = model.CaptainSportEventParticipantId });
            }

            TempData["ManageTeamMessage"] = "Your team has been sucessfully created.";

            return RedirectToAction("ManageTeam", new { sportEventTeamId = model.SportEventTeamId });
        }

        [HttpGet]
        public ActionResult SportEventSelectExistingTeam(Guid id)
        {
            ModelState.AddModelError(string.Empty, (TempData["TeamAllocationErrorMessage"] ?? string.Empty).ToString());

            ViewData.Model = TempData["ExistingTeamModel"] ?? new ExistingTeamModel { SportEventParticipantId = id };

            return View();
        }

        [HttpPost]
        public ActionResult SportEventSelectExistingTeam(ExistingTeamModel model)
        {
            try
            {
                model = sportsEventService.AttemptAllocationToNamedTeam(model);
            }
            catch (BusinessException bex)
            {
                TempData["ExistingTeamModel"] = model;
                TempData["TeamAllocationErrorMessage"] = bex.Message;

                return RedirectToAction("SportEventSelectExistingTeam", new { Id = model.SportEventParticipantId });
            }

            TempData["TeamSelectionConfirmationMessage"] = "The captain of the team you specified will be notified of your request to join the team.";

            return RedirectToAction("TeamSelectionConfirmation");
        }

        [HttpGet]
        public ActionResult TeamSelectionConfirmation()
        {
            ViewBag.ConfirmationMessage = TempData["TeamSelectionConfirmationMessage"];

            return View();
        }


        [HttpGet]
        public ActionResult ManageTeam(Guid sportEventTeamId)
        {
            // TODO: Apply Authorisation to manage teams (only captains should be able to)
            ViewBag.SportEventTeamId = sportEventTeamId;
            ViewBag.TeamMessage = TempData["ManageTeamMessage"];

            ViewData.Model = sportsEventService.ListTeamMembers(sportEventTeamId);

            return View();
        }

        [HttpGet]
        public ActionResult ConfirmTeamMember(Guid sportEventTeamId, Guid sportEventParticipantId)
        {
            sportsEventService.ConfirmTeamMember(sportEventParticipantId);
            return RedirectToAction("ManageTeam", new { sportEventTeamId });
        }

        [HttpGet]
        public ActionResult AddTeamMember(Guid sportEventTeamId)
        {
            ModelState.AddModelError(string.Empty, (TempData["AddTeamMemberErrorMessage"] ?? string.Empty).ToString());

            ViewBag.Months = Enum.GetNames(typeof(Month))
                .AsEnumerable()
                .Select(x => new SelectListItem { Value = x, Text = x });

            ViewBag.Genders = Enum.GetNames(typeof(Gender))
                .AsEnumerable()
                .Select(x => new SelectListItem { Value = x, Text = x });

            NewTeamMemberModel model = TempData["TeamMemberModel"] as NewTeamMemberModel 
                ?? new NewTeamMemberModel { SportEventTeamId = sportEventTeamId };

            if (model.ParticipantAlreadyExists)
            {
                ViewBag.Message = "A participant with the specified email address already exists. You can add this existing participant to your team or change the details you've specified and add a new team member";
            }

            ViewData.Model = model;

            return View();
        }

        [HttpPost]
        public ActionResult AddTeamMember(NewTeamMemberModel model)
        {
            try
            {
                model = sportsEventService.AddNewTeamMember(model);

                if(model.ParticipantAlreadyExists)
                {
                    TempData["TeamMemberModel"] = model;

                    return RedirectToAction("AddTeamMember", new { sportEventTeamId = model.SportEventTeamId });
                }
            }
            catch (BusinessException bex)
            {
                TempData["AddTeamMemberErrorMessage"] = bex.Message;
                TempData["TeamMemberModel"] = model;

ESF.WebClient/Views/SportsEvent/AddTeamMember.cshtml
@model ESF.Core.Services.NewTeamMemberModel

@{
    ViewBag.Title = "Add Team Member";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Team Member</h2>

@ViewBag.Message

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>NewTeamMemberModel</legend>

		@Html.HiddenFor(x => x.SportEventTeamId)

        @if (ViewData.Model.ParticipantAlreadyExists)
        { 
            <div class="editor-label">
                @Html.LabelFor(model => model.AddExistingParticipant, "Add Existing Participant")
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.AddExistingParticipant)
                @Html.ValidationMessageFor(model => model.AddExistingParticipant)
            </div>
        }

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName, "First Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LastName, "Last Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EmailAddress, "Email Address")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmailAddress)
            @Html.ValidationMessageFor(model => model.EmailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthDay, "Birth Day")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthDay)
            @Html.ValidationMessageFor(model => model.BirthDay)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthMonth, "Birth Month")
        </div>
        <div class="editor-field">
            @Html.DropDownList("BirthMonth", (IEnumerable<SelectListItem>)ViewBag.Months)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BirthYear, "Birth Year")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BirthYear)
            @Html.ValidationMessageFor(model => model.BirthYear)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gender)
        </div>
        <div class="editor-field">
            @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.Genders)
        </div>

        <p>
            <input type="submit" value="Add New Team Member" />
        </p>
            
		@Html.ActionLink("Cancel","ManageTeam",new {sportEventTeamId = Model.SportEventTeamId})
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESF.WebClient/Views/SportsEvent/ManageTeam.cshtml
@using ESF.Commons.Utilities
@model IEnumerable<ESF.Core.Services.TeamMemberDetail>

@{
    ViewBag.Title = "Manage Team";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage Team</h2>

@ViewBag.TeamMessage

<table>
    <tr>
        <th>
            Team Member Name
        </th>
        <th>
            Team Member Status
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamMemberName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeamMemberAllocationStatusString)
            </td>
            <td>
                @if(item.TeamMemberAllocationStatusString == TeamAllocationStatus.UnconfirmedTeamMember.GetStringValue())
                {
                    @Html.ActionLink("Confirm as Team Member", "ConfirmTeamMember", new { sportEventTeamId = item.SportEventTeamId, sportEventParticipantId = item.TeamMemberSportEventParticipantId })
                }
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Add a Team Member", "AddTeamMember", new { sportEventTeamId = ViewBag.SportEventTeamId })
</p>

<p>
    @Html.ActionLink("Back to Signed Up Sport Events", "ViewSportsEvents", "SportsEvent")
</p>

ESF.WebClient/Views/SportsEvent/SignUpGrid.cshtml
@model IList<ESF.Core.Services.SportEventGroup>

@{
	ViewBag.Title = "SignUpGrid";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sign Up Grid</h2>

<script type="text/javascript">

	$.fn.ToggleEnabledStates = function (src) {

		var idString = src.attr("overlappingeventids");

		$.each(idString.split(","), function (targetIndex, targetItem) {

			var target = $("#" + targetItem);

			if (src.is(":checked")) {
				target.attr("disabled", "disabled");
			} else {

				var enableTarget = true;
				var targetOverLappingEventIds = target.attr("overlappingeventids");

				$.each(targetOverLappingEventIds.split(","), function (overlappingIndex, overlappingItem) {
					var overlappingEvent = $("#" + overlappingItem);
					if (overlappingEvent.is(":checked")) {
						enableTarget = false;
						return false;
					}
				});

				if (enableTarget) {
					target.removeAttr("disabled");
				}
			}
		});
	};

</script>

@ViewBag.SportEventSignUpMessage

<div class="container">

@using (Html.BeginForm())
{
	@Html.Hidden("participantId", (Guid)ViewBag.ParticipantId)

	foreach (var sportEventGroup in Model)
	{
		var divStyle = sportEventGroup.FestivalDay == 1 ? "one_third_first" : "one_third";
			
		if (sportEventGroup.FestivalDay == 1)
		{
			<br clear="all"/>
		}
	
        <div class="@divStyle">
            <p class="title">@sportEventGroup.ToString()</p>
            <ul style="list-style-type: none; padding:0; margin:0;">
                @foreach (var sportEvent in sportEventGroup.SportEvents)
				{
					var disabled = !sportEvent.IsSelectable ? "disabled" : null;
					
                    <li><input type="checkbox" id="@sportEvent.ScheduledSportEventId" name="@sportEvent.ScheduledSportEventId" checked="@sportEvent.CurrentParticipantAlreadySignedUp" disabled="@disabled" onclick="$(this).ToggleEnabledStates($(this))" overlappingeventids="@sportEvent.OverLappingEventIds"/><label>@sportEvent.ScheduledSportEventName</label></li>
				}
            </ul>
        </div>
	}
    <br clear="all"/>
    <hr/>
    <p>
        <input type="submit" value="Sign Up" />
		<input type="button" onclick="window.location.href='@Url.Action("ViewSportsEvents", "SportsEvent", new { id = ViewBag.ParticipantId })'" value="Cancel" />
	</p>	
}
</div>

ESF.WebClient/Views/SportsEvent/SportEventCreateNewTeam.cshtml
@model ESF.Core.Services.TeamCreateModel

@{
    ViewBag.Title = "SportEventCreateNewTeam";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sport Event Create New Team</h2>

@ViewBag.TeamCreateMessage

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Create New Team</legend>

        @Html.HiddenFor(model => model.CaptainSportEventParticipantId)

        <div class="editor-label">
            @Html.LabelFor(model => model.TeamName, "Team Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TeamName)
            @Html.ValidationMessageFor(model => model.TeamName)
        </div>

        <p>
            <input type="submit" value="Create" />
			<input type="button" onclick="window.location.href='@Url.Action("ViewSportsEvents", "SportsEvent", new { id = ViewBag.ParticipantId })'" value="Cancel" />
        </p>
    </fieldset>
}

ESF.WebClient/Views/SportsEvent/SportEventSelectExistingTeam.cshtml
@model ESF.Core.Services.ExistingTeamModel

@{
    ViewBag.Title = "SportEventSelectExistingTeam";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sport Event Select Existing Team</h2>

@ViewBag.TeamAllocationMessage

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Join Existing Team</legend>

        @Html.HiddenFor(model => model.SportEventParticipantId)

        <div class="editor-label">
            @Html.LabelFor(model => model.TeamName, "Team Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TeamName)
            @Html.ValidationMessageFor(model => model.TeamName)
        </div>

        <p>
            <input type="submit" value="Join" />
        </p>
    </fieldset>
}

<p>
    @Html.ActionLink("Cancel", "ViewSportsEvents", "SportsEvent", new { id = ViewBag.ParticipantId }, null)
</p>

ESF.WebClient/Views/SportsEvent/SportEventTeamSelect.cshtml
@model ESF.Core.Services.TeamSelectionModel

@{
    ViewBag.Title = "Team Selection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Team Selection</h2>

<p>@ViewBag.SportEventTeamSelectMessage</p>
<p>What would you like to do?</p>

@using(Html.BeginForm())
{
    <fieldset>
        <legend>Team Selection</legend>
		@Html.HiddenFor(x => x.ScheduledSportEventParticipantId)
        <div class="editor-field">
            <div>@Html.RadioButtonFor(x => x.TeamSelectionOption, 1) Create a Team</div>
            <div>@Html.RadioButtonFor(x => x.TeamSelectionOption, 2) Join an Existing Team</div>
            <div>@Html.RadioButtonFor(x => x.TeamSelectionOption, 3) Make myself available to any Team that needs a member</div>
        </div>
        <p>
            <input type="submit" value="Next" />
			<input type="button" onclick="window.location.href='@Url.Action("ViewSportsEvents", "SportsEvent", new { id = ViewBag.ParticipantId })'" value="Cancel" />
        </p>
    </fieldset>
}

ESF.WebClient/Views/SportsEvent/TeamSelectionConfirmation.cshtml
@{
    ViewBag.Title = "Team Selection Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Team Selection Confirmation</h2>

<p>@ViewBag.ConfirmationMessage</p>

ESF.WebClient/Views/SportsEvent/ViewSportsEvents.cshtml
@using ESF.Commons.Utilities
@model IEnumerable<ESF.Core.Services.SportEventParticipantModel>

@{
    ViewBag.Title = "View Sports Events";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Sports Events</h2>
<p>
    @ViewBag.Message
</p>
<table>
    <tr>
        <th>
            Sport Event
        </th>
        <th>
            Team Allocation Status
        </th>
        <th>
            Team Name
        </th>
        <th>
        </th>
        <th>
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ScheduledSportEventName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamAllocationStatusString)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @if(item.IsTeamCaptain)
            {
                @Html.ActionLink("Manage Team", "ManageTeam", new { sportEventTeamId = item.SportEventTeamId })
            }
            else if(item.TeamAllocationStatusString != TeamAllocationStatus.NotApplicable.GetStringValue())
            {
                @Html.ActionLink("Change Team Allocation Status", "SportEventTeamSelect", new { id = item.ScheduledSportEventParticipantId })
            }
        </td>
        <td>
            @if(item.CanBeDeleted)
            {
				@Html.ActionLink("Delete Sport", "DeleteSportEventParticipation", new { participantId = ViewBag.ParticipantId, scheduledSportEventParticipantId = item.ScheduledSportEventParticipantId })
            }
        </td>
    </tr>
}
</table>

<p>
    @Html.ActionLink("Sign Up for a Sports Event", "SignUpGrid", new { id = ViewBag.ParticipantId })
</p>

<p>
    @Html.ActionLink("Next", "ViewEntertainment", "Entertainment", new { id = ViewBag.ParticipantId }, null)
</p>